version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Sao_Paulo #optional
      - SUBDOMAINS=bridge
      - TOKEN=token
      - LOG_FILE=false #optional
    volumes:
      - /mnt/duckdns:/config #optional
    restart: always

